context:
  version: "2.10.0"

package:
  name: ui5-webcomponents-react-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@ui5/webcomponents-react-cli/-/webcomponents-react-cli-${{ version }}.tgz
  sha256: 181d3ed8b2a4b1a368b8693048f1a88cc18e15e3e5cb741489f4161df68c02a5

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "ui5-wcr 2>&1 | grep -q \"Unknown command undefined\""

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI for UI5 Web Components for React
  homepage: https://github.com/SAP/ui5-webcomponents-react
  repository: https://github.com/SAP/ui5-webcomponents-react

extra:
  recipe-maintainers:
    - danielnachun
