context:
  version: "2.13.0"

package:
  name: ui5-webcomponents-react-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@ui5/webcomponents-react-cli/-/webcomponents-react-cli-${{ version }}.tgz
  sha256: 928147c345cd48a1e88315809fae8409bd4e40001b8f35eec05fdf3e0da27cbb

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "ui5-wcr 2>&1 | grep -q \"Unknown command undefined\""

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI for UI5 Web Components for React
  homepage: https://github.com/SAP/ui5-webcomponents-react
  repository: https://github.com/SAP/ui5-webcomponents-react

extra:
  recipe-maintainers:
    - danielnachun
