context:
  version: "2.10.1"

package:
  name: ui5-webcomponents-react-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@ui5/webcomponents-react-cli/-/webcomponents-react-cli-${{ version }}.tgz
  sha256: 04481f98d5aeb696a491047f0e4f2636134a8bb916ae4b8ccb36e491f9fe8442

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "ui5-wcr 2>&1 | grep -q \"Unknown command undefined\""

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI for UI5 Web Components for React
  homepage: https://github.com/SAP/ui5-webcomponents-react
  repository: https://github.com/SAP/ui5-webcomponents-react

extra:
  recipe-maintainers:
    - danielnachun
